fn main() {
    // Register the app's own bridge commands with the ACL so they get
    // `allow-<command>` / `deny-<command>` permissions autogenerated. Without
    // this the remote origin (prosto.ink) can't be granted them in a capability
    // (Tauri v2.11+ subjects remote origins to ACL) and EVERY invoke() from the
    // web is rejected — dead titlebar buttons + a splash that only clears via
    // the failsafe. Names are snake_case (the Rust fn names); the generated
    // identifier slugifies `_`→`-` (win_minimize → allow-win-minimize).
    let attributes = tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "win_minimize",
            "win_toggle_maximize",
            "win_close",
            "win_is_maximized",
            "badge_set",
            "badge_clear",
            "notify",
            "popout",
            "app_ready",
            "open_external",
        ]),
    );
    tauri_build::try_build(attributes).expect("failed to run tauri-build");
}
